CREATE DATABASE IF NOT EXISTS barberia CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE barberia;

CREATE TABLE IF NOT EXISTS Reservas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  servicio ENUM('corte', 'disenio_barba', 'afeitado') NOT NULL,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
